### ISSUE TITLE
Use conda-build 2.x

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/conda-forge-build-setup-feedstock#40]
conda build 2.x has [been available for some time now](https://github.com/conda/conda-build/releases) with several important new features and bug fixes.   Several issues have prevented conda-forge from using this version until resolved.  

Hopefully, this issue will track and discuss these issues.

**Comment by jjhelmus** [comment]
One of the big changes in `conda-build 2.x` is the increase in the placeholder path to 255 bytes.  Packages which contain binary prefixes will need to be rebuilt to use these longer paths.    A number of packages in the `conda-forge` channel use "short" prefixes and need to be rebuilt.  These packages [have been identified](https://github.com/conda-forge/conda-forge.github.io/issues/171#issuecomment-248977453), although the channel should be re-scanned to create a more up-to-date list.

Rebuilding these packages may require some "bootstrapping" using existing 255 byte prefix packages from the `default` channel due to circular dependencies (ncurses and pkg_config for instances).

**Comment by jjhelmus** [comment]
Another concern in moving to `conda build 2.x` is that cmake produces errors under conda build 2, see conda-forge/cmake-feedstock#21.  Disabling symbolic linking was suggested in the [2016-11-24 conda-forge Hangout](https://conda-forge.hackpad.com/conda-forge-meetings-2YkV96cvxPG) to solve this problem.  

My own testing in building `blosc` suggests that this action is not needed.  Rather using a more recent version of conda (e.g. 4.2.12), conda-build 2.x, and conda packages of ncurses, openssl and curl which provide 255 bytes prefix placeholders results in a [successful build](https://circleci.com/gh/conda-forge/blosc-feedstock/24?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) without the need to disable symbolic linking.  

There was an bug in conda `4.2.12` with the setting of the conda-build root directory, conda/conda#3744, which may have causes issue for conda-forge but this was fixed in conda `4.2.13`.  A PR to add this version of conda to the `conda-forge` channel was made in the conda-feedstock, conda-forge/conda-feedstock#14, by @jakirkham.  There is a concern that the conda `4.2.x`  line may be causing a slow startup/memory issue on AppVeyor (conda-smithy#351).

**Comment by jjhelmus** [comment]
My own personal recommendation would be as follows:

* add conda `4.2.13` and conda-build `2.0.10` to the `conda-forge` channel while keeping the current pinning to conda-build.
* Rebuild all packages using short binary prefixes manually using a packages from the `defaults` channel as needed to bootstrap.
* Move the pinning in this recipe to conda build 2.x.

Would appreciate hearing what other @conda-forge/core members think about moving to conda build 2.x!

**Comment by msarahan** [comment]
Thank you for writing this up @jjhelmus - I agree completely with your sentiments here.

**Comment by jakirkham** [comment]
Thanks @jjhelmus for writing this up. Also thanks for your work on isolating the `cmake` issues.

Not to make the list any longer, but to release the global pinning we will need to re-render the `conda-forge-build-setup` feedstock and make a new release. The re-rendering is needed to resolve various blocker issues that are difficult to track at this point. As this is only necessary when we release the pinning overall, it can be worked on contemporaneously or after solving some of these other issues.

xref: https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/29
xref: https://github.com/conda-forge/conda-smithy/pull/285

> There is a concern that the conda 4.2.x line may be causing a slow startup/memory issue on AppVeyor (conda-smithy#351).

I'm not sure how we address this issue. Am ok to proceed and start paying it more attention should it arise again.

xref: https://github.com/conda-forge/conda-smithy/issues/351

**Comment by ocefpaf** [comment]
Agreed! (and thanks!)

**Comment by jjhelmus** [comment]
@msarahan Does the 255 character prefix in conda build 2.x effect windows packages?  The `2.0.0` release notes indicate that only Linux and OS X packages need to be rebuilt.  

I want to re-scan the `conda-forge` channel for short prefix packages and wanted to check if I should include windows packages or not.

**Comment by msarahan** [comment]
Yes and no.  They are not limited in the same way that Unix binaries are.  Some executables and libraries do contain prefixes.  Conda-build 2 does detect and record them.  Conda should (and in 4.1 and recent versions of 4.2, does) ignore them.  There's also pip-created launcher executables.  These take special attention to fix the python prefix contained in them.  Conda 4.2 is necessary to handle these properly.  You'd see these if using ```pip install``` when creating the package, if that package has Windows entry points.

To avoid any confusion: no rebuild should be necessary.  Things will work fine without a rebuild.

**Comment by jjhelmus** [comment]
> To avoid any confusion: no rebuild should be necessary. Things will work fine without a rebuild.

Thanks for the insight.  I'll generate a new list of packages that need to be rebuilt excluding Windows packages.

**Comment by jjhelmus** [comment]
I scanned the packages in the `conda-forge` channel for packages which make use of a short binary prefix.  It looks like 44 package will need to be rebuilt:

```
$ python binary_prefix_check_file.py 
bison uses a binary prefix, lengths: [80, 80]
curl uses a binary prefix, lengths: [80, 80]
cycamore uses a binary prefix, lengths: [80, 80]
cyclus uses a binary prefix, lengths: [80, 80]
dbus uses a binary prefix, lengths: [80, 80]
eccodes uses a binary prefix, lengths: [80, 80]
ecmwf_grib uses a binary prefix, lengths: [80, 80]
emacs uses a binary prefix, lengths: [80, None]
flex uses a binary prefix, lengths: [80, 80]
fontconfig uses a binary prefix, lengths: [80, None]
git uses a binary prefix, lengths: [80, 80]
glib uses a binary prefix, lengths: [80, 80]
graphviz uses a binary prefix, lengths: [80, 80]
harfbuzz uses a binary prefix, lengths: [80, None]
hdf5 uses a binary prefix, lengths: [80, 80]
iverilog uses a binary prefix, lengths: [80, 80]
lua uses a binary prefix, lengths: [80, 80]
mpi4py uses a binary prefix, lengths: [80, 80]
ncl uses a binary prefix, lengths: [80, 80]
ncurses uses a binary prefix, lengths: [80, 80]
obspy uses a binary prefix, lengths: [None, 80]
openmc uses a binary prefix, lengths: [80]
openmpi uses a binary prefix, lengths: [80]
openssl uses a binary prefix, lengths: [80, 80]
openturns uses a binary prefix, lengths: [80, 80]
pango uses a binary prefix, lengths: [80, 80]
petsc uses a binary prefix, lengths: [80]
pkg-config uses a binary prefix, lengths: [80, 80]
pyne uses a binary prefix, lengths: [80, None]
pyngl uses a binary prefix, lengths: [80, 80]
pyside uses a binary prefix, lengths: [80, 80]
python-eccodes uses a binary prefix, lengths: [80, 80]
python-ecmwf_grib uses a binary prefix, lengths: [80, 80]
python-spams uses a binary prefix, lengths: [80, 80]
simbody uses a binary prefix, lengths: [80, 80]
slepc uses a binary prefix, lengths: [80, 80]
swig uses a binary prefix, lengths: [80, 80]
texlive-core uses a binary prefix, lengths: [80, 80]
tk uses a binary prefix, lengths: [80, 80]
tokyocabinet uses a binary prefix, lengths: [80, 80]
udunits uses a binary prefix, lengths: [80, 80]
udunits2 uses a binary prefix, lengths: [80, 80]
uwsgi uses a binary prefix, lengths: [None, 80]
vigra uses a binary prefix, lengths: [80, 80]
Uses a binary prefix: 44
Does NOT use a binary prefix: 1403
Total: 1447
```

**Comment by ocefpaf** [comment]
We need a dependency graph to  figure out the build order. Like bison and flex probably need to be built first as they are used to build others. (At least that is my understanding, @msarahan please correct me if I am mistaken.)

I can do that once I get back  (unless someone beats me to it).

**Comment by scopatz** [comment]
Can conda already dump out the dependency graph? Or a sorted version of it?

**Comment by msarahan** [comment]
Not sure this functionality exists in a nice way.  I think conda-build-all constructs a graph, but might be wrong.  @pelson?

I have been playing with graphs a lot at https://github.com/conda/conda-concourse-ci - nothing immediately usable to you from a command line, but might have helpful examples.  See especially https://github.com/conda/conda-concourse-ci/blob/master/conda_concourse_ci/compute_build_graph.py

**Comment by ocefpaf** [comment]
BTW this is how I plan to do:

https://ocefpaf.github.io/python4oceanographers/blog/2014/11/17/networkX/

List those packages that Jonathan found and scan the feedstocks repo.
Hackish but I  think it would work.

**Comment by jjhelmus** [comment]
Example of forcing a feedstock to use conda-build 2.x by manually editing the CI files, conda-forge/tokyocabinet-feedstock#2.  

Once the conda-forge-build-setup scripts move are changed to use conda build 2.x a re-render should remove the additions.

**Comment by jjhelmus** [comment]
> Like bison and flex probably need to be built first as they are used to build others.

I think it will be even more exciting as bison depends on flex, and flex on bison!  The dependency graph will have cycles.

**Comment by msarahan** [comment]
As long as cycles are split between build and run/test, this can be OK. You just have to treat the passes separately. You just can't have a cyclical dependency within build.

**Comment by jjhelmus** [comment]
Luckily the `defaults` channel has long prefix versions of many of the packages (including bison and flex) which have cyclic dependencies.  It should be possible to uses these to build versions for the `conda-forge` channel.

**Comment by jjhelmus** [comment]
Example of forcing a feedstock to use conda-build 2.x and the `defaults` channel as a source of long prefix packages, conda-forge/bison-feedstock#4.  This will be needed to break the cycles in the dependency graphs unless a better solution can be found.

**Comment by jjhelmus** [comment]
To Do list to move to `conda-build` `2.x`.   
I will edit this as items are added/removed:

## Add conda build tools the the `conda-forge` channel.
- [x] Add conda `4.2.x` to `conda-forge` channel, conda-forge/conda-feedstock#14
- [x] Add conda-build `2.x` to `conda-forge` channel, conda-forge/conda-build-feedstock#7

## Rebuild the following packages with a long prefix:
- [x] bison
- [x] cairo
- [x] curl
- [x] cycamore
- [x] cyclus 
- [x] dbus
- [x] eccodes
- [x] ecmwf_grib
- [x] emacs
- [x] esmf
- [x] flex 
- [x] fontconfig
- [x] gdal
- [x] git 
- [x] glib
- [x] graphviz
- [x] harfbuzz
- [x] hdf5
- [x] iverilog - https://github.com/conda-forge/iverilog-feedstock/pull/6
- [x] libiconv
- [x] libnetcdf
- [x] libxslt
- [x] lua - conda-forge/lua-feedstock#13 , conda-forge/lua-feedstock#14 , conda-forge/lua-feedstock#15
- [x] m4
- [x] mpi4py
- [x] ncl
- [x] ncurses,
- [x] netcdf-fortran
- [x] netcdf4
- [x] ~obspy~, waiting on a new release to address prefix issue.
- [x] openmc
- [x] openmpi
- [x] openssl
- [x] openturns - conda-forge/openturns-feedstock#24
- [x] pango
- [x] petsc - conda-forge/petsc-feedstock#5 (not uploading Linux packages)
- [x] pkg-config
- [x] pyferret
- [x] ~pyne~ - conda-forge/pyne-feedstock#7, waiting util new version is released
- [x] pyngl
- [x] pyside - conda-forge/pyside-feedstock#11
- [x] python-eccodes
- [x] python-ecmwf_grib - conda-forge/python-ecmwf_grib-feedstock#18
- [x] python-spams
- [x] pyqt
- [x] r-base - https://github.com/conda-forge/r-base-feedstock/pull/1
- [x] simbody
- [x] slepc - https://github.com/conda-forge/slepc-feedstock/pull/1 (build issues)
- [x] swig
- [x] texlive-core
- [x] tk
- [x] tokyocabinet
- [x] ~udunits~ No longer active
- [x] udunits2
- [ ] uwsgi - conda-forge/uwsgi-feedstock#2 (build issues)
- [x] vigra

## Update pins:
- [x] Move `conda-build` pinning to `2.x` in `conda-forge-build-setup`, #47.
- [x] ~Move `conda-build` pinning to `2.x` in `staged-recipes`~ (Not needed)

## Misc:
- [x] Update conda-smithy to support conda `4.2.x`, conda-forge/conda-smithy#394
- [x] Rebuild python 3.5 with `conda-build` `2.x` to resolve missing `__pycache__` directory, conda-forge/python-feedstock#70.

**Comment by jjhelmus** [comment]
Are both `udunits` and `udunits2` active feedstocks or is one deprecated?  `udunits2` seems to have a more recent version (`2.2.20` vs `2.2.17`).

**Comment by ocefpaf** [comment]
Only udunits2 is active.

**Comment by jjhelmus** [comment]
> Only udunits2 is active.

Thanks. I'll remove udunits from the re-build list.

**Comment by jakirkham** [comment]
FYI have freshened a PR ( https://github.com/conda-forge/conda-smithy/pull/285 ) to allow `conda-smithy` to re-render `conda-forge-build-setup` in PR . Tested it on `conda-forge-build-setup` in PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/30 ) and it works. Would appreciate some people taking a look.

It has been designed so as to be a no-op on otherwise. So should not affect any other feedstocks.

**Comment by jjhelmus** [comment]
I tried to sort the packages needing to be rebuild by hand base upon the dependencies.  This gives a basic order for rebuilding.  Key packages are ncurses, tk, and openssl, which python depends on, and then pkg-config.

- [x] bison : conda-forge/bison-feedstock#4
    - [x] flex : ~conda-forge/flex-feedstock#7~, requires conda-forge/flex-feedstock#8 first
        - [x] iverilog : bison, flex, toolchain, autoconf, gperf, readline : conda-forge/iverilog-feedstock#6

- [x] ncurses, conda-forge/ncurses-feedstock#26
    - [x] lua : conda-forge/lua-feedstock#13 , conda-forge/lua-feedstock#14 , conda-forge/lua-feedstock#15

- [x] openmpi : conda-forge/openmpi-feedstock#7

- [x] openssl : conda-forge/openssl-feedstock#8

- [x] tk : conda-forge/tk-feedstock#13, conda-forge/tk-feedstock#14 (version 8.5.19)

- [x] tokyocabinet : conda-forge/tokyocabinet-feedstock#2


### Requires python (ncurse, openssl, tk)

- [x] dbus : conda-forge/dbus-feedstock#4
    - [x] emacs : libxml, ncurses, dbus, jpeg, libpng, giflib, freetype
- [x] pkg-config : ~conda-forge/pkg-config-feedstock#6~, conda-forge/pkg-config-feedstock#7 merged, conda-forge/pkg-config-feedstock#8


- [x] mpi4py : conda-forge/mpi4py-feedstock#4


- [x] ~obspy~ : conda-forge/obspy-feedstock#10, waiting until a new release is made.

- [x] python-spams : conda-forge/python-spams-feedstock#7

- [x] swig : conda-forge/swig-feedstock#7

- [ ] uwsgi : conda-forge/uwsgi-feedstock#2

### Requires pkg-config (python)

- [x] curl : conda-forge/curl-feedstock#13
    - [x] git : curl, autoconf, expat, openssl, zlib https://github.com/conda-forge/git-feedstock/pull/20

- [x] fontconfig : conda-forge/fontconfig-feedstock#10
    - [x] graphviz : pkg-config, fontconfig, cairo, expat, libpng, libtiff, libtool, ... https://github.com/conda-forge/graphviz-feedstock/pull/5
    - [x] texlive-core : pkg-config, cairo, gmp, icu, mpfr, pixman, freetype, ... https://github.com/conda-forge/texlive-core-feedstock/pull/8

- [x] glib : conda-forge/glib-feedstock#13
    - [x] harfbuzz : pkg-config, glib, perl, automake, libtool, cairo, ...
        - [x] pango : pkg-config, harfbuzz, perl, fontconfig, freetype, libpng

### Requires cmake (curl)

- [x] cyclus : pkg-config, python, toolchain, libxmlpp, curl, **glib**
    - [x] cycamore : pkg-config, cyclus, toolchain, python, cmake

- [x] hdf5 : conda-forge/hdf5-feedstock#55
    - [x] eccodes : cmake, boost, jasper, libpng, libnetcdf, perl https://github.com/conda-forge/eccodes-feedstock/pull/18
        - [x] python-eccodes : python, eccodes, libnetcdf, ...  https://github.com/conda-forge/python-eccodes-feedstock/pull/13
    - [x] ecmwf_grib : cmake, jasper, libpng, libnetcdf, gcc https://github.com/conda-forge/ecmwf_grib-feedstock/pull/20
        - [x] python-ecmwf_grib : python, ecmwf_grib, libnetcdf, cmake, ... https://github.com/conda-forge/python-ecmwf_grib-feedstock/pull/18
    - [x] vigra : python, hdf5, cmake, nose, numpy, jpeg, ...
    - [x] openmc : pkg-config, hdf5, toolchain, cmake, gcc, git, mpich https://github.com/conda-forge/openmc-feedstock/pull/4

- [x] openturns : conda-forge/openturns-feedstock#22

- [x] petsc : python, cmake, blas, mpich, openmpi, ptscotch, ... https://github.com/conda-forge/petsc-feedstock/pull/5 (not uploading Linux packages)
    - [x] slepc : python, mpi, petsc - https://github.com/conda-forge/slepc-feedstock/pull/1

- [x] pyside : ~~conda-forge/pyside-feedstock#5~~ https://github.com/conda-forge/pyside-feedstock/pull/11

- [x] simbody : ~~conda-forge/simbody-feedstock#10~~ https://github.com/conda-forge/simbody-feedstock/pull/11

- [x] udunits2 : conda-forge/udunits2-feedstock#6

### Multiple dependencies (likely build last)

- [x] pyne : pkg-config, hdf5, python, cmake, gcc, blas, ...
- [x] ncl : pkg-config, libnetcdf, curl, udunits, ...
    - [x] pyngl : python, ncl, pkg-config, gcc, numpy, expat, ...

**Comment by ocefpaf** [comment]
Awesome! Thanks for doing this Jonathan!

**Comment by jjhelmus** [comment]
The delays and issues with Travis CI have been slowing progress on rebuilding package with the long prefix but I'm still working on these.  Hopefully the Travis OS X  infrastructure will become more stable and the queue will shorten.

**Comment by jjhelmus** [comment]
## Workflow for creating a long prefix pull request

This is for my own benefit as well as in case anyone else wants to help by submitting some PR to the above packages.

- Fork the feedstock in question and clone.
- Create a new branch, `git checkout -b long_prefix`
- Rerender the feedstock:
    - `conda smithy rerender`
   - `git diff --staged`
   - `git commit -m 'MNT: Re-rendered with conda-smithy 1.6.1'`
- Add the following lines to the `ci_support/run_docker_build.sh` file:

    Right after `source run_conda_build_setup`
    ```

    # install conda-build 2.x to build a long prefix
    conda install --yes --quiet conda-build=2
    conda info
    ```

   Right before the `EOF` line:
   ````

    # inspect the prefix lengths of the built packages
    conda inspect prefix-lengths /feedstock_root/build_artefacts/linux-64/*.tar.bz2
   ````

- Add the following lines to the .travis.yml

    Right after `source run_conda_build_setup`
    ```

        # install conda-build 2.x to build a long prefix
        conda install --yes --quiet conda-build=2
        conda info
    ```

   At the end of the file:
    ```

      # inspect the prefix lengths of the built packages
      - conda inspect prefix-lengths /Users/travis/miniconda3/conda-bld/osx-64/*.tar.bz2
   ```
- Increment the build number in the `recipe/meta.yaml`.
- Create a commit with these changes:
    - `git add .travis.yml ci_support/run_docker_build.sh recipe/meta.yaml`
   - `git commit -m "Build long prefix package using conda-build 2.x"`
- Push the branch to your personal fork and create a pull request.
   - `git push origin long_prefix`

**Comment by jjhelmus** [comment]
`cmake` depends on `curl` so any recipes which have `cmake` as a build requirements will need to be re-build after `curl` is rebuild.  I've adjusted the build order plan accordingly.

**Comment by jakirkham** [comment]
So lots of things are pinned to `fontconfig` version `2.11.*`. However, we rebuilt `fontconfig` version `2.12.1` with `conda-build` 2. So we either need to bump our `fontconfig` pinnings or we need to rebuild the latest version of `fontconfig` `2.11.*`. My recommendation would be the latter as it avoids getting into pinning problems while trying to upgrade `conda-build` as well. Thoughts?

Have proposed this in PR ( https://github.com/conda-forge/fontconfig-feedstock/pull/11 ).

**Comment by jjhelmus** [comment]
> My recommendation would be the latter as it avoids getting into pinning problems while trying to upgrade conda-build as well. Thoughts?

I think making a long prefix build of `fontconfig` version `2.11.x` using `conda-build` 2 while keeping the current pinning is the best path forward.  I did a similar build for `tk` as we pin `8.5.x` and `8.6.x` is out.  

@jakirkham has a PR (conda-forge/fontconfig-feedstock#11) for such a version.  Once the Circle CI issue is resolved I think this should be good to go.

**Comment by jakirkham** [comment]
The `fontconfig` issue is now resolved. CircleCI issues are being discussed out-of-band ( https://github.com/conda-forge/status/issues/30 ).

**Comment by pelson** [comment]
A long time ago, in a galaxy far far away, I did write a crappy dependency viewer (build+run deps as I recall) for conda-forge. The repo is in https://github.com/pelson/conda-forge-deps, and you can see an example (after the server has fetched all of the data, so you will get timed out for the first minute or so) at https://conda-forge-deps.herokuapp.com/img/readline. 

I'd love to see this done well. I'd certainly change the underlying architecture to http 202 until the data is available (and only then 200). Realistically, this is so far down my priority list that I'm not going to touch it for months, but that doesn't mean it wouldn't be extremely useful! 😄

**Comment by jjhelmus** [comment]
A few additional package have a binary prefix when they are rebuilt with `conda-build` 2.  Luckily these already support a long prefix, thanks @ocefpaf , but I am adding them to the list:

* cairo
* m4
* libiconv
* libnetcdf
* netcdf-fortran
* netcdf4

I expect to see more packages listing binary prefixes as `conda-build` 2 is rolled out.  The new version seem to switch from an opt-in prefix list of binary files to opt-out.  Unless stripped of debugging symbols most binary files will include the build prefix and will be included in the `has_prefix` file.  This should not cause any issues but is something to keep in mind.

**Comment by jjhelmus** [comment]
@msarahan Is the change from opt-in to opt-out for including binary files in `has_prefix` intentional in `conda-build` 2?  I think it is overall a good thing but might be a bit surprising to some.  

The only issue I've encountered so far with rewriting prefixes in binary files is with the `python` package when used with `constructor` to create an installed.  Bad things happen (memory/bus errors) when trying to rewrite `libpython.xxx.so` in a process that is using that library as is done in the installed.  Explicitly excluding this shared library with `ignore_prefix_files` should fix this issue I just have not had time to test it fully.

**Comment by msarahan** [comment]
Yes, it's intentional.  I thought it would cover more beginner user error.  Relocatability is hard, and people shouldn't need to learn how to do it, if we can avoid it.

That libpython special case is something that maybe we can add to conda-build or to constructor (or both) to avoid issues, IMHO.

**Comment by jjhelmus** [comment]
> That libpython special case is something that maybe we can add to conda-build or to constructor (or both) to avoid issues, IMHO.

constructor is where this should be implemeted in my opinion.  I believe if the file was removed prior to writing the version with the replaced prefix, the mmap into the running process would be fine.  This is getting off topic so I'll open an issue in `constructor` on the topic once I've had a chance to test it.

**Comment by jakirkham** [comment]
Re-rendering `conda-forge-build-setup` in PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/43 ).

Edit: This has been merged.

**Comment by jakirkham** [comment]
Responding to one of the items.

> Move conda-build pinning to 2.x in staged-recipes

staged-recipes also uses conda-forge-build-setup. So there is no need to handle this separately. This is just part of updating the pinning in conda-forge-build-setup.

**Comment by jjhelmus** [comment]
Added a few additional packages to the list that have binary prefixes:

* esmf
* gdal
* libxslt
* lxml
* r-base
* pyferret
* pyqt

**Comment by jjhelmus** [comment]
Summary of work on moving to `conda-build` 2.  I will update this comment as work progresses.

1 packages remain that should be rebuilt to support a long prefix:

## Waiting on maintainers to review and merge

* ~~lua - conda-forge/lua-feedstock#13 , conda-forge/lua-feedstock#14 , conda-forge/lua-feedstock#15~~
* ~~python-ecmwf_grib - conda-forge/python-ecmwf_grib-feedstock#18~~

## Open pull request with issue(s) that need to be solved

* ~~pyside - conda-forge/pyside-feedstock#11 : Some builds exceed maximum time limit~~
* uwsgi - conda-forge/uwsgi-feedstock#2 : OS X build fails for unknown reason
* ~~petsc - conda-forge/petsc-feedstock#5 : not uploading Linux packages (related to following point)~~
* ~~slepc - conda-forge/slepc-feedstock#1 : Linux build is a short prefix due to missing dependency~~

## Not sure how to rebuild

* gdal : pins a version of swig that is a short prefix build

I've submitted an update to `conda-forge-build-setup`, #47, to remove the pinning to `conda-build` 1 so that version 2.x is used.  Despite the handful of packages needing to be re-build, I think this switch can be made at this point.

Edit: I've updates the list crossing out all but one item.  `uwsgi` still uses a short prefix but rebuilding does not seem to work on OS X.  The maintainers have not weighed in on the topic so I'm moving on.

**Comment by ocefpaf** [comment]
Agreed. I'll ssubmit the swig version need for gdal soon and fix gdal's
prefix.

**Comment by jakirkham** [comment]
There's a couple PRs that could use a review and merge.

* [x] https://github.com/conda-forge/lua-feedstock/pull/13
* [x] https://github.com/conda-forge/lua-feedstock/pull/14
* [x] https://github.com/conda-forge/lua-feedstock/pull/15
* [x] https://github.com/conda-forge/python-ecmwf_grib-feedstock/pull/18

**Comment by jakirkham** [comment]
We are now on `conda-build` 2. They are a few remaining items to address here. So will leave open until we have finished them.

**Comment by jakirkham** [comment]
Summarizing the status as I understand. Please feel free to correct any omissions or misunderstandings.

As far as long prefix stuff, it looks like we are down to `gdal` and `uwsgi`.

WRT `uwsgi`, we have had trouble building it and the maintainer has been unresponsive. Getting it fixed looks to be non-trivial and none of the stack is using it ATM. So my recommendation is leave the PR in place and move on.

I don't know what is going on with `gdal` ATM. Has it been rebuilt ok? Maybe someone else can share.

Other remaining issues include rebuilding Python 3.5 with `conda-build` 2 and building `conda-build` 2.

Anything else?

**Comment by jjhelmus** [comment]
I agree with your summary @jakirkham, thanks for posting.  @ocefpaf is the expert on `gdal` so perhaps he can speak to it's status.  

I submitted conda-forge/python-feedstock#105 to build Python 3.5 with `conda-build` 2 to solve the __pycache__ issue.  

I can't think of anything else that needs to be done!  Time to move on to Python 3.6!?!

**Comment by jjhelmus** [comment]
The only packages I'm seeing with short prefixes are:

* fenics
* obspy
* pyne
* udunits
* uwsgi

All of those except `fenics` have been discussed above.  

`gdal` 2.1.2 builds 5 and 6 seems to have long prefixes.

**Comment by jakirkham** [comment]
> All of those except `fenics` have been discussed above.

That's strange. It looks like `fenics` was rebuilt [2 days ago]( https://github.com/conda-forge/fenics-feedstock/commits/655b0e9bec33d7acd3d01922d1547ede4ef56e8c ) with `conda-build` 2.

**Comment by jakirkham** [comment]
Downloaded 2 recent packages (OS X and Linux) from `fenics` and inspected them manually. They appear to both be using the `255` character prefix length as expected.

**Comment by jjhelmus** [comment]
> They appear to both be using the 255 character prefix length as expected.

I'm seeing the same thing, I think `fenic` is fine now.

I'm in favor of closing this issue.  I think the move to `conda-build` 2.x is done.  The remaining short prefix packages are aware of that fact and the updates to them can be tracked in the feedstocks.

**Comment by jakirkham** [comment]
Were there any other non-prefix related `conda-build` 2 tasks that are still outstanding? If not, I'm also in favor of closing.

**Comment by jjhelmus** [comment]
> Were there any other non-prefix related conda-build 2 tasks that are still outstanding?

Not that I know of.  Closing! :fireworks: :fireworks:

**Comment by yohannLelievre** [comment]
Hi,
First, I would like to thank you for your work. Indeed, I've been able to build a miniconda package from the CRAN yesterday (anaconda.org/BiRD/r-isa2)!
This morning, I tried to build a miniconda package from a github library (vqv/ggbiplot) and I fell on an other placeholder-problematic package : 'bioconda::r-tibble-1.2-r3.3.1_0'.
Here is the error returned.

`ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'bioconda::r-tibble-1.2-r3.3.1_0'.
PaddingError: Placeholder of length '80' too short in package /sandbox/ylelievre/miniconda3/conda-bld/r-ggbiplot_1485248602176/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/R/library/tibble/libs/tibble.so.
The package must be rebuilt with conda-build > 2.0.`

Am I at the good place to report this issue?
What can I do to solve it?

cc @jjhelmus

**Comment by jjhelmus** [comment]
@yohannLelievre As the error message indicates the way to solve this issue is to rebuilt the package in question (r-tibble) with conda-build > 2.0.  

As for reporting the issue, if the package is from the `conda-forge` channel then please open an issue in the feedstock repository for that package.  It looks like the package is from the `bioconda` channel, I do not know where to report issues with packages in that group but https://github.com/bioconda/bioconda-recipes might be a possibility.

**Comment by yohannLelievre** [comment]
Thank you for your reply! I will investigate toward the bioconda group.

**Comment by jakirkham** [comment]
I know the bioconda group is working on getting at least the basic R stack in conda-forge. Though I don't know how this package sits in that stack or whether it is planned to move it as well. Maybe worth asking them about this as well. If so, this would be resolved simply by moving it here.

**Comment by yohannLelievre** [comment]
It seems that, meanwhile, the bioconda group has finally rebuilt the package r-tibble. Thank you again for your replies.
